#!/bin/bash

############
# WEBUX HELPER FUNCTIONS
# General: repositories must live in the same parent folder
#
# dependencies:
#  --  USER variable; from bash_profile
#		a string containing the user name
#  --  REPOS array; from bash_profile
#		an array of valid project repositories
#  --  bgwatch function required; from functions-dev
#       runs grunt watcher in the background
# --  getRepo function required; from functions-dev
#      returns name of current repository
############

test -f functions-dev && . $_

function runwraith {
    repo=$(getRepo)
    if [[ $repo == "webux" || $repo == "webux-alt" ]]; then
        watch_pid=$(bgwatch)
        echo "#--- Running ${1:-$USER} wraith"
        wraith ${1:-$USER} wraith/baseline_pages.yaml &>/dev/null
        kill -9 $watch_pid && return $!
    fi
}